services:

  postgres:
    image: postgres:16
    container_name: etl-postgres
    environment:
      POSTGRES_DB: etl_database
      POSTGRES_USER: etl_user
      POSTGRES_PASSWORD: etl_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: